language: node_js

notifications:
    email:
        - yiminghe@gmail.com

node_js:
  - 10.15.0

script:
  - npm test
  - npm run-script cover
  - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
